test tailscale 1

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -21,6 +21,18 @@ inputs:
 runs:
     using: 'composite'
     steps:
+      - name: Check Runner OS
+        if: ${{ runner.os != 'Linux' }}
+        shell: bash
+        run: |
+          echo "::error title=⛔ error hint::Support Linux Only"
+          exit 1
+      - name: Check Auth Key Empty
+        if: ${{ inputs.authkey == '' }}
+        shell: bash
+        run: |
+          echo "::error title=⛔ error hint::Auth key empty, Maybe you need to populate it in the Secrets for your workflow, see more in https://docs.github.com/en/actions/security-guides/encrypted-secrets"
+          exit 1
       - name: Download Tailscale
         shell: bash
         id: download
@@ -46,5 +58,5 @@ runs:
         run: |
           sudo tailscaled &
           HOSTNAME="github-$(cat /etc/hostname)"
-          echo tailscale up --authkey ${TAILSCALE_AUTHKEY} --hostname=${HOSTNAME} --accept-routes ${ADDITIONAL_ARGS}
-          sudo tailscale up --authkey ${TAILSCALE_AUTHKEY} --hostname=${HOSTNAME} --accept-routes ${ADDITIONAL_ARGS}
+          echo tailscale up --authkey ${{ inputs.authkey }} --hostname=${HOSTNAME} --accept-routes ${ADDITIONAL_ARGS}
+          sudo tailscale up --authkey ${{ inputs.authkey }} --hostname=${HOSTNAME} --accept-routes ${ADDITIONAL_ARGS}
